services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - 6333:6333 # REST API
      - 6334:6334 # gRPC
      
    environment:
      QDRANT__SERVICE__API_KEY: "${ENV_VAR_QDRANT_API_KEY}"
    volumes:
      - ./data/qdrant:/qdrant/storage
